### ISSUE TITLE
Geometry Crashed 

### ISSUE THREAD

**Issue by asinmhk** [shad0wta9/meshavatar#7]
The training code always crashed in 'geometry/dmtet.py', line 299.
AssertionError: The geometry crashed (no triangles)! Please restart the program!

Could you provide some tips?

>Loading model from: anaconda3/envs/meshavatar/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth 
anaconda3/envs/meshavatar/lib/python3.9/site-packages/torch/nn/functional.py:4236: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
Using .cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file .cache/torch_extensions/py39_cu117/renderutils_plugin/build.ninja...
Building extension module renderutils_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
Loading extension module renderutils_plugin...
anaconda3/envs/meshavatar/lib/python3.9/site-packages/torch/nn/functional.py:4236: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
iter=    0, deformation_loss=0.022641, perc_loss=0.016108, img_loss=0.357745, reg_loss=0.279262, lr=0.00000, time=401.2 ms, rem=11.15 h
iter=  100, deformation_loss=0.003107, perc_loss=0.013854, img_loss=0.361274, reg_loss=0.279484, lr=0.00010, time=350.2 ms, rem=9.72 h
Traceback (most recent call last):
  File "meshavatar/train.py", line 473, in <module>
    geometry, mat = optimize_mesh(glctx, geometry, mat, lgt, dataset_train, dataset_validate,
  File "meshavatar/train.py", line 314, in optimize_mesh
    losses = trainer(target, it + FLAGS.start_iter, denoiser)
  File "anaconda3/envs/meshavatar/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "meshavatar/train.py", line 178, in forward
    return self.geometry.tick(glctx, target, self.light, self.material, self.image_loss_fn, it, denoiser, self.perc_loss_fn)
  File "meshavatar/geometry/dmtet.py", line 333, in tick
    buffers, cano_pos, motion_feat = self.render(glctx, target, lgt, opt_material, denoiser, shadow_ramp, training=True)
  File "meshavatar/geometry/dmtet.py", line 299, in render
    assert False, "The geometry crashed (no triangles)! Please restart the program!"
AssertionError: The geometry crashed (no triangles)! Please restart the program!

**Comment by asinmhk** [comment]
Sry, the same as [issue #6](https://github.com/shad0wta9/meshavatar/issues/6#issue-2504959238)
